# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_overview',
                'doc_host': 'https://curator8.github.io',
                'git_url': 'https://github.com/curator8/nbdev_overview',
                'lib_path': 'nbdev_overview'},
  'syms': {'nbdev_overview.core': {'nbdev_overview.core.foo': ('core.html#foo', 'nbdev_overview/core.py')}}}
